version: '3.8'

services:
  trading-agent:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: binance-trading-agent
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      - BINANCE_API_URL=${BINANCE_API_URL:-https://testnet.binance.vision}
      - MCP_SERVER_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - REDIS_HOST=redis
    ports:
      - "8081:8080"  # MCP Server (changed to avoid port conflict)
      - "9091:9090"  # Monitoring/Metrics (changed to avoid prometheus conflict)
      - "8502:8501"  # Streamlit Web UI (changed to avoid port conflict)
    volumes:
      - ./data:/app/data  # Persist SQLite databases
      - ./logs:/app/logs  # Persist logs
      - ./config.toml:/app/config.toml:ro  # Configuration
    networks:
      - trading-network
    restart: unless-stopped
    # Health check removed - MCP server uses stdio, not HTTP

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - trading-network

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - trading-network
    profiles:
      - monitoring

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - trading-network
    profiles:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  trading-network:
    driver: bridge