name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black isort pip-audit pytest pytest-asyncio

      - name: Lint with ruff
        run: ruff binance_trade_agent

      - name: Format check with black
        run: black --check binance_trade_agent

      - name: Import sort check with isort
        run: isort --check binance_trade_agent

      - name: Run tests
        run: pytest binance_trade_agent/tests/ --disable-warnings -v

      - name: Security audit
        run: pip-audit
